package org.wattdepot.resource.sensordata;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertTrue;
import javax.xml.datatype.XMLGregorianCalendar;
import org.wattdepot.util.tstamp.Tstamp;
import org.junit.Test;
import org.wattdepot.resource.sensordata.jaxb.Properties;
import org.wattdepot.resource.sensordata.jaxb.Property;
import org.wattdepot.resource.sensordata.jaxb.SensorData;
import org.wattdepot.resource.sensordata.jaxb.SensorDataRef;

/**
 * Ensures that the equals() and hashCode() methods that have been manually added to the JAXB
 * autogenerated code are working. This is important, because if the schema files are changed and
 * new Java code is generated via XJC, then the manually added methods will be silently blown away.
 * These tests act as a backstop to ensure that if that happens, tests will fail.
 * 
 * If we eventually move to autogenerated equals() and hashCode() via XJC plugins, then these tests
 * will confirm that the plugins are working properly.
 * 
 * @author Robert Brewer
 */
public class TestSensorDataJaxb {

  /** Making PMD happy. */
  private static final String JUNIT_TOOL = "JUnit";
  /** Making PMD happy, at the expense of readability. */
  private static final String DEFAULT_TIMESTAMP = "2009-07-28T08:00:00.000-10:00";

  /**
   * Tests equals and hashCode for the SensorData Property type.
   */
  @Test
  public void testSensorDataProperty() {
    String key = "some-key", value = "some-value";
    Property prop1 = SensorDataUtils.makeSensorDataProperty(key, value), prop2 =
        SensorDataUtils.makeSensorDataProperty(key, value);

    assertNotSame("Two newly created SensorData Property are the same object", prop1, prop2);
    assertEquals("Two SensorData Property with identical keys and values are not equal", prop1,
        prop2);
    assertEquals("Two SensorData Property with identical keys and values have different hashCodes",
        prop1.hashCode(), prop2.hashCode());
  }

  /**
   * Tests equals and hashCode for the SensorData Properties type.
   */
  @Test
  public void testSensorDataProperties() {
    String key1 = "some-key", value1 = "some-value", key2 = "foo-key", value2 = "foo-value";
    // Make two pairs of Property objects that have same keys &values
    Property prop1 = SensorDataUtils.makeSensorDataProperty(key1, value1);
    Property prop2 = SensorDataUtils.makeSensorDataProperty(key2, value2);
    Property prop3 = SensorDataUtils.makeSensorDataProperty(key1, value1);
    Property prop4 = SensorDataUtils.makeSensorDataProperty(key2, value2);
    Properties props1 = new Properties(), props2 = new Properties();

    props1.getProperty().add(prop1);
    props1.getProperty().add(prop2);
    props2.getProperty().add(prop3);
    props2.getProperty().add(prop4);

    assertNotSame("Two newly created SensorData Properties are the same object", props1, props2);
    assertEquals(
        "Two SensorData Properties with lists of identical Property objects are not equal", props1,
        props2);
    assertEquals("Two SensorData Properties with identical lists have different hashCodes", props1
        .hashCode(), props2.hashCode());
  }

  /**
   * Tests equals and hashCode for the SensorData type.
   * 
   * @throws Exception If there are problems creating the timestamp
   */
  @Test
  public void testSensorData() throws Exception {
    String key1 = "some-key", value1 = "some-value", key2 = "foo-key", value2 = "foo-value";
    // Make two pairs of Property objects that have same keys &values
    Property prop1 = SensorDataUtils.makeSensorDataProperty(key1, value1);
    Property prop2 = SensorDataUtils.makeSensorDataProperty(key2, value2);
    Property prop3 = SensorDataUtils.makeSensorDataProperty(key1, value1);
    Property prop4 = SensorDataUtils.makeSensorDataProperty(key2, value2);
    Properties props1 = new Properties(), props2 = new Properties();
    SensorData data1, data2;

    props1.getProperty().add(prop1);
    props1.getProperty().add(prop2);
    props2.getProperty().add(prop3);
    props2.getProperty().add(prop4);

    XMLGregorianCalendar timestamp1 = Tstamp.makeTimestamp(DEFAULT_TIMESTAMP);
    XMLGregorianCalendar timestamp2 = Tstamp.makeTimestamp(DEFAULT_TIMESTAMP);
    data1 =
        SensorDataUtils.makeSensorData(timestamp1, JUNIT_TOOL,
            "http://localhost:8183/wattdepot/sources/saunders-hall", props1);
    data2 =
        SensorDataUtils.makeSensorData(timestamp2, JUNIT_TOOL,
            "http://localhost:8183/wattdepot/sources/saunders-hall", props2);

    assertNotSame("Two newly created SensorData are the same object", data1, data2);
    assertEquals("Two SensorData objects with identical fields are not equal", data1, data2);
    assertEquals("Two SensorData objects with identical fields have different hashCodes", data1
        .hashCode(), data2.hashCode());
  }

  /**
   * Tests toString for the SensorData type.
   * 
   * @throws Exception If there are problems creating the timestamp
   */
  @Test
  public void testToString() throws Exception {
    String key1 = "foo-key", value1 = "foo", key2 = "bar-key", value2 = "bar";
    Property prop1 = SensorDataUtils.makeSensorDataProperty(key1, value1);
    Property prop2 = SensorDataUtils.makeSensorDataProperty(key2, value2);
    Properties props1 = new Properties();
    SensorData data1;

    props1.getProperty().add(prop1);
    props1.getProperty().add(prop2);

    XMLGregorianCalendar timestamp1 = Tstamp.makeTimestamp(DEFAULT_TIMESTAMP);
    data1 =
        SensorDataUtils.makeSensorData(timestamp1, JUNIT_TOOL,
            "http://localhost:8183/wattdepot/sources/saunders-hall", props1);
    assertEquals("SensorData did not create expected toString",
        "SensorData [properties=[Property [key=foo-key, value=foo], Property [key=bar-key,"
            + " value=bar]], source=http://localhost:8183/wattdepot/sources/saunders-hall,"
            + " timestamp=2009-07-28T08:00:00.000-10:00, tool=JUnit]", data1.toString());
  }

  /**
   * Tests equals, hashCode, and compareTo for the SensorDataRef type.
   * 
   * @throws Exception If there are problems creating timestamps
   */
  @Test
  public void testSensorDataRef() throws Exception {
    // Create a bunch of components we can use to make various SensorDataRefs that will compare
    // differently. "Equal" suffix means the same as the original, "Before" means should compare
    // less than, "After" means should compare greater than.
    XMLGregorianCalendar timestamp = Tstamp.makeTimestamp(DEFAULT_TIMESTAMP);
    XMLGregorianCalendar timestampEqual = Tstamp.makeTimestamp(DEFAULT_TIMESTAMP);
    XMLGregorianCalendar timestampBefore = Tstamp.makeTimestamp("2009-07-27T08:00:00.000-10:00");
    XMLGregorianCalendar timestampAfter = Tstamp.makeTimestamp("2009-07-29T08:00:00.000-10:00");
    String tool = JUNIT_TOOL;
    String toolEqual = JUNIT_TOOL;
    String toolBefore = "A-JUnit";
    String toolAfter = "Z-JUnit";
    String source = "http://server.wattdepot.org:1234/sources/saunders-hall";
    String sourceEqual = "http://server.wattdepot.org:1234/sources/saunders-hall";
    String sourceBefore = "http://server.wattdepot.org:1234/sources/a-saunders-hall";
    String sourceAfter = "http://server.wattdepot.org:1234/sources/z-saunders-hall";
    SensorDataRef ref = SensorDataUtils.makeSensorDataRef(timestamp, tool, source);
    SensorDataRef refEqual =
        SensorDataUtils.makeSensorDataRef(timestampEqual, toolEqual, sourceEqual);
    assertNotSame("Two newly created SensorDataRefs are the same object", ref, refEqual);
    assertEquals("Two SensorDataRefs with identical fields are not equal", ref, refEqual);
    assertEquals("Two SensorDataRefs with identical fields have different hashCodes", ref
        .hashCode(), refEqual.hashCode());
    assertEquals("SensorDataRef.compareTo timestamp not working", 0, ref.compareTo(refEqual));
    SensorDataRef refTimestampBefore =
        SensorDataUtils.makeSensorDataRef(timestampBefore, tool, source);
    SensorDataRef refTimestampAfter =
        SensorDataUtils.makeSensorDataRef(timestampAfter, tool, source);
    assertEquals("SensorDataRef.compareTo timestamp not working", -1, ref
        .compareTo(refTimestampAfter));
    assertEquals("SensorDataRef.compareTo timestamp not working", 1, ref
        .compareTo(refTimestampBefore));
    SensorDataRef refToolBefore = SensorDataUtils.makeSensorDataRef(timestamp, toolBefore, source);
    SensorDataRef refToolAfter = SensorDataUtils.makeSensorDataRef(timestamp, toolAfter, source);
    assertTrue("SensorDataRef.compareTo tool not working", ref.compareTo(refToolAfter) < 0);
    assertTrue("SensorDataRef.compareTo tool not working", ref.compareTo(refToolBefore) > 0);
    SensorDataRef refSourceBefore = SensorDataUtils.makeSensorDataRef(timestamp, tool, sourceBefore);
    SensorDataRef refSourceAfter = SensorDataUtils.makeSensorDataRef(timestamp, tool, sourceAfter);
    assertTrue("SensorDataRef.compareTo source not working", ref.compareTo(refSourceAfter) < 0);
    assertTrue("SensorDataRef.compareTo source not working", ref.compareTo(refSourceBefore) > 0);
  }
}
